experiment_name: 'default_p1'

### DELETE ME, just for double checking default configs run with environment specs
device: 1

data:
    features_path: '../data/cll/panel1/x_all_8d_1p.pkl'
    labels_path: '../data/cll/panel1/y_all_8d_1p.pkl'

n_run: 5
