experiment_name: 'baseline_plots_100->200'
n_epoch: 100
n_run: 1 # CV handled in loop for this experiment
n_folds_for_cluster_CV: 5
test_size: 0.0 # splitting is handled in loop - all 102 samples used to train and oos test data used to eval
device: 1
gate_size_default: [.5, .5]
#100 for .25 10 otherwise
num_clusters_grid: [5, 30]
use_out_of_sample_eval_data: True # using oos data to make the plots
out_of_sample_eval_data: '../data/cll/8d_FINAL/x_test_1p.pkl'
out_of_sample_eval_labels: '../data/cll/8d_FINAL/y_test_1p.pkl'
node_type: 'square'

init_type: 'heuristic_init'
heuristic_init:
        num_gridcells_per_axis: 4
        use_greedy_filtering: False
        consider_all_gates: False


hard_gates_at_the_end: True
corner_init_deterministic_size: .5
output:
    type: 'lightweight'
data:
    features_path: '../data/cll/8d_FINAL/x_all_8d_1p.pkl' #'../data/cll/8d/x_dev_8d_1p.pkl' #'../data/cll/8d_fixed_24242_removed_29842/x_dev_8d_1p.pkl' 
    labels_path: '../data/cll/8d_FINAL/y_all_8d_1p.pkl' #'../data/cll/8d/y_dev_8d_1p.pkl'   #'../data/cll/8d_fixed_24242_removed_29842/y_dev_8d_1p.pkl'
#seven_epochs_for_gate_motion_plot: [0, 35, 70, 150, 250, 350, 450]
#seven_epochs_for_gate_motion_plot: [0,2, 4, 5, 6, 7, 10]
#seven_epochs_for_gate_motion_plot: [0, 75, 150, 200, 245, 290, 350]
#seven_epochs_for_gate_motion_plot: [0, 75, 150, 200, 300, 350, 400]
#seven_epochs_for_gate_motion_plot: [0, 25, 50, 75, 100, 150, 200]
seven_epochs_for_gate_motion_plot: [0, 10, 25, 50, 60, 75, 100]
#seven_epochs_for_gate_motion_plot: [0, 5, 15, 25, 35, 45, 50]
run_logistic_to_convergence: True


two_phase_training:
    turn_on: False
    num_only_log_loss_epochs: 0 #200
    num_random_inits_for_log_loss_only: 1 #30
    min_gate_size: .1


plot_params:
    figsize: [21, 12]
    marker_size: .1
#seven_epochs_for_gate_motion_plot: [0, 140, 280, 320, 460, 600, 750]
#n_run: 1
