experiment_name: 'default_p1'

### DELETE ME, just for double checking default configs run with environment specs
device: 1

data:
    features_path: '../data/cll/8d_FINAL/x_all_8d_1p.pkl'
    labels_path: '../data/cll/8d_FINAL/y_all_8d_1p.pkl'
