experiment_name: 'logreg_to_conv_noreg' #'logreg_to_conv_gate_size=1_everything_else=0'
n_epoch: 100
n_epoch_eval: 10 #100
test_size: 0.0

gate_size_penalty: 0.0
regularization_penalty: 0.
negative_box_penalty: 0.
corner_penalty: 0.

batch_size: 35
learning_rate_gates: .05 
learning_rate_classifier: .05 

#init_type: 'random'
init_type: 'middle'
output:
    type: 'lightweight'
data:
    features_path: '../data/cll/x_dev_4d_1p.pkl'
    labels_path: '../data/cll/y_dev_4d_1p.pkl'
seven_epochs_for_gate_motion_plot: [0, 15, 30, 45, 60, 75, 99]
run_logistic_to_convergence: True
#seven_epochs_for_gate_motion_plot: [0, 140, 280, 320, 460, 600, 750]
#n_run: 1
